# This is a basic workflow that is manually triggered
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


name: testrun



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testrun:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2

#    - name: Install packages
#      run: |
#        R -e 'install.packages("beepr")'
# Run R script
    - name: testrun
      run: Rscript test.R



